# ----------------------------------------------------------------------------
#
# Package             : isobject
# Source Repo         : https://github.com/jonschlinkert/isobject
# Travis Job Link     : https://travis-ci.com/github/rajesh-ibm-power/isobject/builds/230576722
# Created travis.yml  : No
# Maintainer          : Rajesh kumar <Rajesh.kumar13@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ---

sudo: false
arch:
  - amd64
  - ppc64le
os:
  - linux
  - osx
language: node_js
node_js:
  - node
  - '12'
  - '10'
  - '8'
matrix:
  allow_failures: []
  fast_finish: true
git:
  depth: 10
